baseURL = 'https://nils.photos/'
languageCode = 'en-us'
title = 'nils.photos'
disableKinds = ["section", "taxonomy", "term"]

timeout = "5m"

[params]
    [params.umami]
        id = "2d8dc53e-fdfd-401e-b5f6-4e1e8eeaaa5b"
        src = "https://umami.nils.moe/script.js"
    [params.gallerydeluxe]
        # Shuffle the images in the gallery to give the impression of a new gallery each time.
        shuffle = false

        # Reverse the order of the images in the gallery.
        reverse = true

         # Enable Exif data in the gallery.
         # See https://gohugo.io/content-management/image-processing/#exif-data for how to filter tags.
        enable_exif = false

[caches]
    [caches.images]
        dir    = ':cacheDir/gallerydeluxe'
        maxAge = "4320h"                   # 6 months.

[imaging]
    anchor         = "Smart"
    resampleFilter = "CatmullRom"
    quality        = 75
    [imaging.exif]
        disableDate    = false
        disableLatLong = true
        includeFields  = 'Artist|LensModel|FNumber|ExposureTime'

[server]
    [[server.headers]]
        for = '/**'
        [server.headers.values]
            Referrer-Policy = 'strict-origin-when-cross-origin'

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "layouts"
        target = "layouts"
    [[module.mounts]]
        source = "content"
        target = "content"
    [[module.mounts]]
        source = "static"
        target = "static"
    [[module.imports]]
        path = "github.com/bep/gallerydeluxe"

